### ISSUE TITLE
Issues with link related options

### ISSUE THREAD

**Issue by Rnksts** [emvaized/circle-mouse-gestures#13]
CMG is often adding/removing slashes at the end of the domains, affecting all the options that use the link in some way (copy, preview, open it...). This is happening on both Chromium and Firefox. Examples:

| Slash Removed | Slash Added |
| --- | --- |
| ![KHEyAymXAPQT](https://user-images.githubusercontent.com/20311303/182040039-43278722-1940-4452-8885-4d13b4500eeb.png) | ![ef6iLC3TrUHb](https://user-images.githubusercontent.com/20311303/182040082-6f8f49b3-3971-4cbe-8d74-345eae18edb9.png) |

Not to open more issues, a couple more things:
- The "show regular action if no action selected" is ignoring the "+ second action"s, regular right click menu will still display after a combo.
- Would it be possible to use middle click to open the menu?

**Comment by emvaized** [comment]
Thanks for your report. 
I'll publish an update with fix for extra slash in URLs, and for regular menu still showing if "second action" was performed.

As for "middle click to open the menu" — no, currently there's no such an option. 
Despite it would be great to have an option to open the menu with other mouse buttons, such as Middle click or side back/forward buttons, which some mouses have — current version of extension relies a lot on right mouse click under the hood, and I have no plans to rework it in the foreseeable future.

**Comment by emvaized** [comment]
I just pushed update 1.3.8 with fixes for these issues, which should be approved within a few days
