### ISSUE TITLE
request: open link options for image menu

### ISSUE THREAD

**Issue by HapHazard1** [emvaized/circle-mouse-gestures#17]
Frequently an image on a page has a link to some other page.  For a normal link on a page we have the link options to choose from (open link in new tab, etc.) when configuring CMG.  For the Image menu in CMG configuration there are no options to do anything with the underlying link.  To be clear, I am talking about the situation where html looks like this:

`<a href="http://somelink.com"><img src="http://images.com/theimage.jpg" /></a>`

CMG will allow: copy the image link, downloading the image, etc. but there is no way to get CMG to operate on the href link which is "under" the image.  I would like to have CMG access to the href link available as configuration options on the Image menu.

**Comment by emvaized** [comment]
I'm thinking about adding a new type of menu, "Image + link", which will appear in these cases and allow to set actions for both image and link. 

Will it satisfy your needs, or would you rather prefer if CMG combined both "Image" and "Link" menus in one?

**Comment by HapHazard1** [comment]
Either of those options sounds good to me!  I think I like the "Image + link" menu maybe a bit more but I think either solution will work.

**Comment by emvaized** [comment]
"Image + link" type of menu is available in the new version `1.5.2`
