### ISSUE TITLE
Hide menu when mouse outside circle

### ISSUE THREAD

**Issue by kontosa** [emvaized/circle-mouse-gestures#18]
Would you consider an option to deselect the highlighted action if the mouse moves outside the circle? 
Currently whatever action the mouse exits the circle from, stays highlighted - but I was expecting once outside the circle no action should occur when releasing the mouse button? 
I find I have to move back into the middle of the circle to then release the mouse (I have a habit of moving the mouse a bit much!).
An alternative option could be to just close the menu once outside the circle - after a configurable delay (e.g. like 'Selection Search' extn can).

**Comment by emvaized** [comment]
Hi Craig, 
You can not think of any real life use cases which could benefit from such option. Current behavior is intended to allow for wide gestures when your intent is one of the outside actions, so you don't have to aim for them precisely to select.

**Comment by kontosa** [comment]
Ok thanks for considering it.
