### ISSUE TITLE
Very nice extension, hopefully you can adjust the default zoom of the preview link and the size of the default display box   

### ISSUE THREAD

**Issue by ydivho12123** [emvaized/circle-mouse-gestures#27]
Very nice extension, hopefully you can adjust the default zoom of the preview link and the size of the default display box

**Comment by emvaized** [comment]
I'm afraid, setting default zoom of the preview link might not be possible due to how such preview is created. I recommend you to try alternative action "Open link in popup window", which may support custom zoom.
