### ISSUE TITLE
[bug] cannot bring back menu after deleting last level

### ISSUE THREAD

**Issue by deathtrip** [emvaized/circle-mouse-gestures#30]
After you delete the last level for a menu, there's no way to readd new levels.
The "+" option is gone, and the preview overlays with the general settings.

**Comment by emvaized** [comment]
Sorry to hear that you faced such an inconvenience! 
I couldn't confirm this bug on my setup – when I delete the last level for a menu, "plus" button still remains, as well as the preview zone: 

<img width="1099" alt="Screenshot" src="https://github.com/user-attachments/assets/ec745555-b326-4fca-bcf5-160963e82d8d">
 
Although I noticed that the whole settings section shifted too much to the center of the screen when no menu is added. Maybe this behavior in your case caused the "+" button to go off-screen on the right?

**Comment by deathtrip** [comment]
This is how it looks on my setup:
![circlegestures](https://github.com/user-attachments/assets/b1df60a7-5471-4b2e-8efc-cf635acbdb6d)
The general settings moved to where the levels were.
It seems that the "plus" button might be hidden behind the general settings.

**Comment by emvaized** [comment]
I see now! I guess this options page was never tested before on ultrawide monitors. 

I'll think about the best way to solve this problem. But for now you can get around it by reducing the overall width of the browser window until the "common settings" block will be shifted to the bottom, revealing the "plus" button.

**Comment by emvaized** [comment]
I figured out this problem was caused by the code which centered settings in the screen. I disabled it for now in the new version `1.5` of the extension, as it was buggy anyway. Maybe will reimplement in the future.
