### ISSUE TITLE
Animation Does Not Often Show Up On The First Image Selection In Google Search Images Results 

### ISSUE THREAD

**Issue by the-phuctran** [emvaized/circle-mouse-gestures#4]
In Google images results, The first long click on a selected image often not show up circle animation, but the second long click does.
My problem video: https://streamable.com/qjgzz9

**Comment by emvaized** [comment]
In the new version 1.3.6 there was small improvements for the show-up animation – perhaps it may resolve this issue

**Comment by emvaized** [comment]
Since I can no longer detect any problems with animation, I close this issue as a resolved. Please open a new one if you'll face any new issues.
