### ISSUE TITLE
[Feature Request] export/import of settings

### ISSUE THREAD

**Issue by huyz** [emvaized/circle-mouse-gestures#9]
At least through Chrome Sync, but preferably through Google Drive, as the uBlacklist extension does, which would make the settings syncable between Chrome and Brave browsers and across multiple profiles.

**Comment by emvaized** [comment]
Thanks for your suggestion!

However, I don't think settings sync is really needed in this extension, as it is not meant to be regularly reconfigured; it's more like one-time setup after install, and then use with occasional changes to your liking – unlike uBlacklist, where you're supposed to edit website rules on the go.

And not to mention users may like to have different actions set on different devices, which narrows down the number of users who can benefit from settings sync even further.

Therefore I don't think the amount of time and effort spent developing this feature correlates with its usefulness for this particular extension.
However, I'm planning to implement manual import/export feature, as it feels much more relevant.

**Comment by huyz** [comment]
True, an import/export would be sufficient for most cases.

**Comment by katastrophe92** [comment]
@emvaized import/export would be awesome and more key bindings or ways to open the quick wheel. BTW i just found this adon and I'm in love. Thanks for the work.

**Comment by emvaized** [comment]
Import/export/reset settings buttons will be finally available in the new version 1.4.5

Sorry it took that long! Enjoy 😊
